name: Tag Created

on:
  - create
  - workflow_dispatch

jobs:
  abracadabra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            
            // Matches tags that end with SemVer, e.g. v1.0.1-alpha+20201101.build3
            const semver_tag_without_prefix_regex = /^refs\/tags\/(v?((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?))$/;
            tag_ref = context.ref;
            const match = tag_ref.match(semver_tag_without_prefix_regex);

            if (match === null) { core.setFailed(`not a SemVer tag`); return; }

            const is_prerelease = match[6] === undefined ? false : true;
            
            console.log("repo owner:", context.repo.owner);
            console.log("repo name:", context.repo.repo);
            console.log("tag:", match[1]);
            console.log("is prerelease:", is_prerelease);
            
            github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: match[1],
            }).then(res => {
              console.log(res);
            });
            //console.log("ex rel:", existing_release);
            
            /*github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: match[1],
              draft: true,
              prerelease: is_prerelease,
            });*/
