name: Tag Created

on:
  create:
    tags:
      - v2*

jobs:
  abracadabra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            console.log(context)
