name: Tag Created

on:
  - create
  - workflow_dispatch

jobs:
  abracadabra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            //console.log("gh ref:", context.github.ref);
            console.log("ref:", context.ref);
            console.log("owner:", context.repo.owner);
            console.log("repo:", context.repo.repo);
            
            // Tags that ends with SemVer, e.g. aaa/v1.0.1-alpha+20201101.build3
            const semver_tag_with_prefix_regex = /^refs\/tags\/(v?((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?))$/;
            tag_ref = context.ref;
            const match = tag_ref.match(semver_tag_with_prefix_regex);

            if (match === null) { core.setFailed(`not a SemVer tag`); }
            console.log(`${match[1]}`);
            const is_prerelease = match[6] === undefined ? false : true;
            console.log("prerelease:", is_prerelease);
            
            /*github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: match[1],
              draft: true,
              prerelease: is_prerelease,
            });*/
